"""FastAPI backend for the AuraAgent GUI.

Calls the exact same core/bootstrap.py::build_app_context() the CLI
(main.py) does, swapping in a WebSocketConfirmationChannel + WebSocketSink
instead of TerminalConfirmationChannel + TerminalSink — everything else
(the tool registry, the team, all six self-extension tools) is identical.
This is the architectural guarantee behind "CLI and GUI stay feature-equal"
(see core/bootstrap.py's module docstring).

M1 scope (this module): a single shared AppContext for the whole process's
lifetime — one shared backend, matching main.py's own single-process model.
Multiple SIMULTANEOUS connections (the desktop GUI plus a connected
Auralis phone, or two browser tabs) ARE supported (N14): each gets its own
WebSocketSink queue (keyed by a per-connection `connection_id`, see
gui/ws_log_sink.py) so one connection's events can never be delivered to a
different one's socket, and its own `active_session` local, so switching
chats on one connection never touches another's. What is NOT supported is
two connections' turns actually running at the same instant —
`ctx.run_lock` (held for the full duration of a turn, and for any other
action that touches the shared workspace_root/active_project/Leader state:
the initial connect-time sync, "new_chat", "set_active_session") still
serializes ALL of that, GUI and CLI and the scheduler alike, exactly as
before. A second connection's message just waits for the lock like
everything else always has; it is never corrupted by what the first
connection is doing. Chat *sessions* (below) are a different thing from
connections: many sessions can be saved, and now more than one CAN be live
across different connections at once, each on its own connection's own
`active_session`.

Auth (N14): when `settings.require_auth` is on (see gui/auth.py and
config/settings.py's AURA_REQUIRE_AUTH — off by default, so a purely local
setup is unaffected), every REST route requires a valid device Bearer
token (tools/devices/device_store.py) and `/ws` requires one as a `?token=`
query param, checked BEFORE accept() so an unauthorized socket is never
even opened. This is what makes it safe to put this process behind a
Cloudflare Tunnel for a real Auralis phone to reach.

Sessions (persistence across restarts, tools/sessions/session_store.py):
each connection has an "active session" — SessionSink (gui/session_sink.py)
appends every event into that session's own file as it happens, so a
conversation survives a server restart and can be resumed later, not just
within one connection's lifetime the way Epic N1's `history` alone would
be. On connect, the most-recently-updated session is resumed automatically
(or a fresh one is created if none exist yet) — "open AuraAgent, see your
last conversation" is the whole point. `history` (the actual per-connection
conversation memory the Leader engine reads) is reconstructed from a
session's persisted top-level user_input/final_answer events, not stored
as a second, redundant representation — see `cli/service.py::history_from_events()`
(shared with telegram_bot.py, the Telegram frontend -- moved there so neither
frontend duplicates this reconstruction logic).
Deliberately simplified versus the engine's real internal `history` (which
also carries raw provider tool-call turns, per AsyncReActEngine's own
docstring): resuming a session gives the model back the conversational
gist (what was asked, what was answered), not an exact tool-call replay.
This is the same tradeoff essentially every consumer chat product makes,
and keeps a saved session provider-agnostic (switching LLM provider between
sessions never corrupts one).

A session's title is auto-generated by a lightweight, tool-free LLM call
after its first exchange (see `_maybe_autoname_session`) if it's still the
default placeholder — this never blocks or fails the actual chat turn (see
that function's own try/except). A human can always override it via the
sidebar's rename control (PATCH /api/sessions/{id}, gui/routes.py) — the
one shared `ChatSessionStore.rename_session()` path handles both.

Project/directory <-> Chat sync (see `_sync_active_directory`): a chat can
optionally belong to a Project (`SessionInfo.project_slug`) and/or carry
its own working directory (`SessionInfo.directory`, only actually used
while it has no Project tag -- a Project always outranks it). Whenever a
chat becomes the active one on this connection (initial connect,
"new_chat", "set_active_session"), `cli/service.py::sync_active_directory()`
re-resolves which directory/Project actually governs it -- now always
under `ctx.run_lock` (N14), since this mutates the same shared
workspace_root/active_project/Leader state a turn does, and two
connections doing this "at the same time" (e.g. one switches chats while
another's turn is mid-flight) must not interleave. `_run_orchestrator()`
calls the exact same function again, right before every single turn,
also inside `ctx.run_lock` -- not just relying on the chat-switch sync
above, so a turn's directory can never be left stale by whatever ran in
between (a scheduled task, another connection). See that function's own
docstring for the full priority chain and the bug this replaced
(workspace_root used to be a single global value /workspace set and
/project use would silently clobber back and forth).

Per-connection routing (N14): `sink.current` and `session_sink
.active_session_id` both say "route the next event to THIS one" --
exactly like `ctx.workspace_root`/`ctx.active_project`, these are shared,
process-wide pointers, so every place that sets them (the three spots
above, plus `_run_orchestrator`) does so only while holding `ctx.run_lock`,
for the same reason. Each connection also keeps its own `active_session`
local (never read back from `session_sink.active_session_id`, which could
have moved on to a different connection by the time it's read) -- this is
what `user_message` sends into `_run_orchestrator` as `session_id`, not
the shared pointer.

M2 adds the actual frontend (gui/frontend/, a minimal React+Vite app) —
`npm run build` there outputs straight into gui/static/, which this module
mounts and serves at "/" whenever that directory exists, so a single
`uvicorn gui.server:app` serves both the WebSocket API and the built UI.
If gui/static/ hasn't been built yet (e.g. in tests, or before running
`npm run build`), "/" simply isn't mounted and /ws still works fine on its
own — that's how M1 was exercised before any frontend existed, with a raw
WebSocket client/script.

Wire protocol (JSON messages):
  Server -> client: every AuraLogger event (user_input/calling_llm/
    thought/tool_call/observation/confirmation/final_answer/error — see
    core/logger.py), PLUS confirmation_request / open_question_request
    (from ConfirmationChannel, see gui/ws_channel.py), PLUS session_loaded
    (payload: {id, title, events}, sent right after connecting and after
    new_chat/set_active_session), session_renamed (payload: {id, title}),
    quick_note_sync_ack (payload: {accepted_client_ids: [...]}), and
    sync_catchup (payload: {schedule_results: [...], active_project:
    {slug, name} | null} — see _build_sync_catchup, sent in reply to a
    client's own "hello") — all share the same {event_type, payload, ...}
    shape on one ordered stream, routed to the ONE connection that caused
    them (gui/ws_log_sink.py's `current` pointer). PLUS schedule_result
    (payload: {schedule_id, task, summary} — see
    tools/scheduler/scheduler_loop.py), the one event type that's
    BROADCAST to every connected device instead of routed to one (a
    finished background task isn't "this connection's" event the way
    everything else here is).
  Client -> server: {"type": "user_message", "text": "..."} to run the
    orchestrator; {"type": "confirmation_response", "request_id": ...,
    "approved": true|false}; {"type": "open_question_response",
    "request_id": ..., "answer": "..."}; {"type": "new_chat",
    "project_slug": "..." (optional)} to start a brand-new saved session,
    tagged to that Project if given, else to whichever Project is currently
    active (if any); {"type": "set_active_session", "session_id": "..."}
    to switch to an existing one (its list comes from GET /api/sessions,
    gui/routes.py); {"type": "quick_note_sync", "items": [{"client_id":
    ..., "text": ..., "captured_at": ...}]} -- a phone's offline-captured
    quick notes, each appended as a Thino-style bullet into ITS OWN day's
    daily note file (see _append_quick_notes) once connectivity resumes;
    {"type": "hello", "last_synced_at": "..." (optional ISO timestamp)} --
    sent once right after connecting (N14, e.g. by a reconnecting Auralis
    phone) to request a sync_catchup reply bundling what it missed, instead
    of it separately polling several REST endpoints itself.

IMPORTANT concurrency note: handling "user_message" must NEVER block this
handler's `while True: await websocket.receive_text()` loop. orchestrator
.run() can itself block inside a ConfirmationChannel.confirm() call,
waiting for a "confirmation_response" message — and that message can only
ever arrive by this SAME loop reaching receive_text() again. Running the
orchestrator inline here would deadlock: the run() that's waiting for a
response would itself be what's preventing that response from ever being
read. So "user_message" is dispatched as a background asyncio.Task, never
awaited directly in the receive loop.

Epic N1 gives each connection a persistent `history` list, passed into
every `ctx.orchestrator.run(text, history=history)` call so the Leader
actually remembers earlier turns within one connection. Because
"user_message" runs as a background Task rather than being awaited inline,
a SECOND "user_message" arriving while the first is still running would
race on that same mutable list — so "user_message" (and "new_chat"/
"set_active_session", which reassign `history` outright) are rejected
whenever `run_tasks` already shows a run in flight; the frontend already
disables its input while busy, this is just the server-side enforcement.
"""
from __future__ import annotations

import asyncio
import json
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any, AsyncIterator

from pathlib import Path
from uuid import uuid4

from fastapi import Depends, FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles

from cli import service
from config.settings import Settings, load_settings
from core.bootstrap import AppContext, build_app_context
from core.logger import AuraLogger, JSONLSink
from core.message_types import ConversationTurn
from gui.auth import check_ws_token, require_device_token
from gui.graph_routes import router as graph_router
from gui.routes import router as api_router
from gui.session_sink import SessionSink
from gui.sync_routes import router as sync_router
from gui.ws_channel import WebSocketConfirmationChannel
from gui.ws_log_sink import WebSocketSink
from tools.notes.thino_format import insert_thino_line, parse_captured_at
from tools.projects.project_tool import register_project_chat_search_tool
from tools.sandbox_path import resolve_within_sandbox
from tools.sessions.session_store import DEFAULT_TITLE, ChatSessionStore, SessionInfo

#: Where `npm run build` (gui/frontend/) outputs the production bundle —
#: exposed at module level (not just a local inside create_app()) so
#: gui_app.py (Epic M4's desktop entry point) can check it exists and give
#: a clear message before ever opening a window against a backend with no
#: UI mounted.
STATIC_DIR = Path(__file__).resolve().parent / "static"


def create_app(settings: Settings | None = None) -> FastAPI:
    """`settings` is injectable so tests can pass a Settings pointed at
    tmp_path sandboxes (same pattern as tests/test_bootstrap.py) instead
    of requiring a real .env/API key — `uvicorn gui.server:app` (the real
    entry point, see the module-level `app` below) always uses the real
    load_settings()."""

    @asynccontextmanager
    async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
        resolved_settings = settings if settings is not None else load_settings()
        sink = WebSocketSink()
        session_store = ChatSessionStore(resolved_settings.chat_sessions_dir)
        session_sink = SessionSink(session_store)
        logger = AuraLogger([JSONLSink(resolved_settings.logs_dir), sink, session_sink])
        confirmation_channel = WebSocketConfirmationChannel(sink, logger)
        app.state.ctx = await build_app_context(resolved_settings, confirmation_channel, logger)
        app.state.sink = sink
        app.state.session_store = session_store
        app.state.session_sink = session_sink
        # search_project_chats needs a ChatSessionStore -- a GUI-only
        # concept build_app_context() never sees (see
        # tools/projects/project_tool.py's module docstring) -- so it's
        # registered here, after both it and ctx exist, rather than
        # inside build_app_context() like the other three project tools.
        # orchestrator's capabilities (config/agents.json) already lists
        # its name, so no leader_view widening is needed once it exists.
        register_project_chat_search_tool(
            app.state.ctx.registry,
            app.state.ctx.active_project,
            session_store,
            lambda: session_sink.active_session_id,
            app.state.ctx.agent_registry.leader.name,
        )
        # Skills staged via POST /api/skills/stage but not yet committed
        # (Epic M3) -- in-memory only, keyed by a uuid; same "small,
        # process-lifetime pending state" shape as ws_channel.py's
        # pending-Futures dict, just for a two-step HTTP flow instead of a
        # WebSocket round trip.
        app.state.staged_skills = {}
        try:
            yield
        finally:
            await app.state.ctx.aclose()

    app = FastAPI(title="AuraAgent GUI backend", lifespan=_lifespan)
    app.include_router(api_router, dependencies=[Depends(require_device_token)])
    app.include_router(sync_router, dependencies=[Depends(require_device_token)])
    app.include_router(graph_router, dependencies=[Depends(require_device_token)])

    @app.websocket("/ws")
    async def websocket_endpoint(websocket: WebSocket) -> None:
        # Checked BEFORE accept() (N14) -- an unauthorized socket is never
        # opened at all, not accepted-then-closed. No-op (always True) when
        # settings.require_auth is off, which is the default -- see
        # gui/auth.py.
        ctx: AppContext = websocket.app.state.ctx
        if not await check_ws_token(websocket, ctx.device_store, ctx.settings.require_auth):
            return
        await websocket.accept()
        sink: WebSocketSink = websocket.app.state.sink
        session_store: ChatSessionStore = websocket.app.state.session_store
        session_sink: SessionSink = websocket.app.state.session_sink
        # ctx.confirmation_channel is a SwappableConfirmationChannel (see
        # confirmation/swappable_channel.py) -- .current is the real
        # WebSocketConfirmationChannel this method needs .resolve() on.
        # Safe to grab once here rather than re-reading .current on every
        # message: a scheduled run can only ever swap it away while
        # holding ctx.run_lock, which a live turn on THIS connection also
        # holds for its own entire duration (see main.py/_run_orchestrator's
        # own `async with ctx.run_lock:`), so it can never be swapped out
        # from under an in-flight confirmation round trip.
        confirmation_channel = ctx.confirmation_channel.current
        assert isinstance(confirmation_channel, WebSocketConfirmationChannel)
        leader_name = ctx.agent_registry.leader.name

        # Own queue for this connection alone (N14) -- see gui/ws_log_sink.py's
        # module docstring for why a shared queue across connections isn't safe.
        connection_id = str(uuid4())
        sink.register(connection_id)
        drain_task = asyncio.create_task(sink.drain(connection_id, websocket))
        # Tracks in-flight orchestrator runs so they can be cancelled if
        # the connection drops, and so asyncio doesn't warn about a task
        # result never being retrieved (see _run_orchestrator's own
        # try/except for the "surface errors instead of losing them" half).
        # Also doubles as the busy flag guarding `history` below: non-empty
        # means a run is in flight on this connection right now.
        run_tasks: set[asyncio.Task[None]] = set()

        # Resume the most-recently-updated saved session, or start a fresh
        # one if this is the very first connection ever -- "open AuraAgent,
        # see your last conversation" (see module docstring). `history` is
        # reconstructed from that session's own persisted events, NOT
        # stored separately -- see service.history_from_events(). Under run_lock
        # (N14): this sets the shared active_session_id/sink.current
        # pointers and mutates ctx's shared workspace_root/active_project
        # state, same as a turn does -- must not interleave with another
        # connection doing the same or with a turn in flight.
        async with ctx.run_lock:
            existing = await session_store.list_sessions()
            active_session = existing[0] if existing else await session_store.create_session()
            session_sink.active_session_id = active_session.id
            sink.current = connection_id
            active_events = session_store.read_events(active_session.id)
            history: list[ConversationTurn] = service.history_from_events(active_events, leader_name)
            await _sync_active_directory(ctx, active_session, sink, leader_name)
            sink.write(_session_loaded_event(active_session, active_events))

        try:
            while True:
                raw = await websocket.receive_text()
                message = json.loads(raw)
                msg_type = message.get("type")
                if msg_type == "user_message":
                    if run_tasks:
                        ctx.logger.log_error(
                            -1,
                            "Ignored: a previous message is still being processed on this connection.",
                            agent_name=leader_name,
                        )
                        continue
                    # This connection's OWN active session, never read back
                    # from the shared session_sink.active_session_id
                    # pointer -- by the time this task actually runs (or
                    # even by the time it's scheduled, if another
                    # connection's action slips in first), that pointer may
                    # already belong to a different connection (N14).
                    session_id = active_session.id
                    task = asyncio.create_task(
                        _run_orchestrator(
                            ctx, message["text"], history, session_store, sink, session_sink, connection_id, session_id
                        )
                    )
                    run_tasks.add(task)
                    task.add_done_callback(run_tasks.discard)
                elif msg_type == "confirmation_response":
                    confirmation_channel.resolve(message["request_id"], message["approved"])
                elif msg_type == "open_question_response":
                    confirmation_channel.resolve(message["request_id"], message["answer"])
                elif msg_type == "new_chat":
                    # Sidebar "New chat": a brand-new saved session, not
                    # just a cleared display -- guarded by the same busy
                    # check as user_message so it can't race a run in flight.
                    # Tagged to the Project named in the message (the
                    # Project detail view's own "+ New chat"), else to
                    # whichever Project is currently active, if any -- a
                    # new chat started while "inside" a Project belongs to
                    # it automatically, no manual tagging step needed.
                    if run_tasks:
                        ctx.logger.log_error(
                            -1,
                            "Ignored: wait for the current turn to finish before starting a new chat.",
                            agent_name=leader_name,
                        )
                    else:
                        async with ctx.run_lock:
                            project_slug = message.get("project_slug") or ctx.active_project.current_slug
                            active_session = await session_store.create_session(project_slug=project_slug)
                            session_sink.active_session_id = active_session.id
                            sink.current = connection_id
                            history = []
                            await _sync_active_directory(ctx, active_session, sink, leader_name)
                            sink.write(_session_loaded_event(active_session, []))
                elif msg_type == "set_active_session":
                    # Sidebar: switch to a previously-saved session (its
                    # list comes from GET /api/sessions). Reconstructs
                    # `history` from that session's own persisted events so
                    # the Leader actually continues it, not just re-displays it.
                    if run_tasks:
                        ctx.logger.log_error(
                            -1,
                            "Ignored: wait for the current turn to finish before switching chats.",
                            agent_name=leader_name,
                        )
                    else:
                        target = await session_store.get_session(message["session_id"])
                        if target is None:
                            ctx.logger.log_error(
                                -1, f"No such chat session '{message['session_id']}'.", agent_name=leader_name
                            )
                        else:
                            async with ctx.run_lock:
                                active_session = target
                                session_sink.active_session_id = target.id
                                sink.current = connection_id
                                target_events = session_store.read_events(target.id)
                                history = service.history_from_events(target_events, leader_name)
                                await _sync_active_directory(ctx, target, sink, leader_name)
                                sink.write(_session_loaded_event(target, target_events))
                elif msg_type == "quick_note_sync":
                    accepted = _append_quick_notes(ctx, message.get("items", []))
                    # Re-assert (N14): `await websocket.receive_text()` above
                    # is a real yield point another connection's own action
                    # could run during, same reasoning as every other
                    # sink.current assignment in this handler.
                    sink.current = connection_id
                    sink.write(
                        {
                            "ts": datetime.now(timezone.utc).isoformat(),
                            "event_type": "quick_note_sync_ack",
                            "payload": {"accepted_client_ids": accepted},
                        }
                    )
                elif msg_type == "hello":
                    catchup = await _build_sync_catchup(ctx, message.get("last_synced_at"))
                    sink.current = connection_id
                    sink.write(
                        {
                            "ts": datetime.now(timezone.utc).isoformat(),
                            "event_type": "sync_catchup",
                            "payload": catchup,
                        }
                    )
                # An unrecognized message type is silently ignored rather
                # than closing the connection — matches main.py's REPL,
                # which tolerates a blank/malformed line without crashing
                # the whole session over it.
        except WebSocketDisconnect:
            pass
        finally:
            drain_task.cancel()
            sink.unregister(connection_id)
            for task in run_tasks:
                task.cancel()

    if STATIC_DIR.is_dir():
        app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")

    return app




async def _sync_active_directory(
    ctx: AppContext, session: SessionInfo, sink: WebSocketSink, leader_name: str
) -> None:
    """Keeps the active Project/directory in lockstep with whichever chat
    just became active (see module docstring) -- delegates entirely to
    cli/service.py::sync_active_directory(). _run_orchestrator() below
    calls that same shared function again, unconditionally, right before
    every single turn; this call here just makes the switch visible
    immediately (e.g. in the Leader's system prompt) without waiting for
    the human to send a message first. Swallows a stale Project reference
    (the chat was tagged to a Project that has since been deleted) rather
    than blocking the chat switch over it; the chat itself keeps its
    now-dangling tag, same as ProjectStore never cascading a delete onto
    anything that referenced it."""
    try:
        await service.sync_active_directory(
            ctx.cli_context, project_slug=session.project_slug, directory_override=session.directory
        )
    except ValueError as exc:
        ctx.logger.log_error(-1, f"Could not switch to this chat's project: {exc}", agent_name=leader_name)


def _session_loaded_event(info: SessionInfo, events: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "ts": datetime.now(timezone.utc).isoformat(),
        "event_type": "session_loaded",
        "payload": {"id": info.id, "title": info.title, "events": events},
    }


async def _run_orchestrator(
    ctx: AppContext,
    text: str,
    history: list[ConversationTurn],
    session_store: ChatSessionStore,
    sink: WebSocketSink,
    session_sink: SessionSink,
    connection_id: str,
    session_id: str,
) -> None:
    is_first_exchange = not history
    try:
        # Shared with tools/scheduler/scheduler_loop.py's own runs -- see
        # main.py's matching `async with ctx.run_lock:` for why.
        async with ctx.run_lock:
            # Re-assert the routing pointers (N14) -- another connection's
            # own action (a chat switch, its own turn) may have repointed
            # sink.current/session_sink.active_session_id to itself while
            # this task was merely scheduled, waiting its turn for
            # run_lock. Every event this turn produces from here on must
            # land on THIS connection's queue and THIS session's file.
            sink.current = connection_id
            session_sink.active_session_id = session_id
            # Defensive re-sync: the chat-switch-time sync above (module
            # docstring) already set the right directory when this chat
            # became active, but re-resolving it again here, right before
            # the turn actually runs, means this turn is correct
            # regardless of whatever happened in between (a scheduled
            # task, a directory change from another connection) -- see
            # cli/service.py::sync_active_directory()'s own docstring.
            # Cheap no-op when nothing has actually changed.
            session = await session_store.get_session(session_id)
            if session is not None:
                try:
                    await service.sync_active_directory(
                        ctx.cli_context, project_slug=session.project_slug, directory_override=session.directory
                    )
                except ValueError as exc:
                    ctx.logger.log_error(-1, f"Could not resolve this chat's directory: {exc}")
            answer = await ctx.orchestrator.run(text, history=history)
    except Exception as exc:  # noqa: BLE001 - surface to the GUI's event stream, mirroring main.py's REPL
        ctx.logger.log_error(-1, f"{type(exc).__name__}: {exc}")
        return
    await session_store.touch(session_id)
    if is_first_exchange:
        await _maybe_autoname_session(ctx, session_store, sink, connection_id, session_id, text, answer)


async def _maybe_autoname_session(
    ctx: AppContext,
    session_store: ChatSessionStore,
    sink: WebSocketSink,
    connection_id: str,
    session_id: str,
    user_text: str,
    answer_text: str,
) -> None:
    """Best-effort: a title generated from the first exchange is a nice
    touch, not something the actual chat turn should ever fail over. Only
    fires if the title is still the default placeholder -- a session
    renamed manually (e.g. right after creation, before sending anything)
    is left alone."""
    info = await session_store.get_session(session_id)
    if info is None or info.title != DEFAULT_TITLE:
        return
    try:
        response = await ctx.provider.send(
            "Generate a short, specific title (3-6 words, no quotes, no trailing punctuation) for a chat "
            "that starts with this exchange. Reply with ONLY the title text, nothing else.",
            [ConversationTurn(role="user", text=f"User: {user_text}\n\nAssistant: {answer_text}")],
            [],
        )
        title = (response.thought_text or "").strip().strip('"').strip("'").strip()
    except Exception:  # noqa: BLE001 - see docstring: auto-naming never breaks the actual chat turn
        return
    if not title:
        return
    try:
        updated = await session_store.rename_session(session_id, title)
    except ValueError:
        return
    # Best-effort re-assert (N14): this runs after run_lock was already
    # released (see _run_orchestrator), so another connection's action
    # could in principle repoint sink.current first -- low-stakes if it
    # does (the rename itself, above, is already correctly persisted by
    # session_id regardless; only this live notification could then reach
    # the wrong tab), so this isn't itself wrapped in another lock.
    sink.current = connection_id
    sink.write(
        {
            "ts": datetime.now(timezone.utc).isoformat(),
            "event_type": "session_renamed",
            "payload": {"id": updated.id, "title": updated.title},
        }
    )


def _append_quick_notes(ctx: AppContext, items: list[dict[str, Any]]) -> list[str]:
    """Routes each item into ITS OWN day's daily note file (by
    captured_at's date, not necessarily "today" -- a phone syncing an
    offline backlog may span several days), under
    `ctx.cli_context.quick_notes_subdir` (default "Daily Notes",
    configurable via /notes quickdir -- see cli/service.py), formatted as
    one Thino-style bullet: `- HH:MM:SS <text verbatim>`, no tag
    parsing/rewriting -- whatever the phone sent (with or without an
    inline #tag, wherever positioned) is passed straight through. This is
    a deterministic, no-judgment-call operation, so it's done directly
    here rather than through the LLM/ToolRegistry layer -- see
    tools/notes/thino_format.py for the shared formatting logic also used
    by the LLM-facing save_quick_note tool (same module). Returns the
    client_ids actually written, for the quick_note_sync_ack reply."""
    accepted: list[str] = []
    for item in items:
        text = item.get("text")
        client_id = item.get("client_id")
        if not text or not client_id:
            continue
        when = parse_captured_at(item.get("captured_at"))
        daily_note_path = resolve_within_sandbox(
            ctx.cli_context.notes_root.current,
            f"{ctx.cli_context.quick_notes_subdir}/{when.strftime('%Y-%m-%d')} 日记.md",
        )
        insert_thino_line(daily_note_path, f"- {when.strftime('%H:%M:%S')} {text}")
        accepted.append(client_id)
    return accepted


async def _build_sync_catchup(ctx: AppContext, last_synced_at: str | None) -> dict[str, Any]:
    """N14 (Auralis / remote access): answers a reconnecting client's
    "hello" by bundling what it missed into ONE reply, instead of making
    it separately poll GET /api/schedules etc. itself. `last_synced_at`
    is the client's own last-successful-sync timestamp (ISO string, or
    None/missing if it has never synced before -- in which case every
    schedule with a recorded run is included, not just recent ones).

    Known limitation, deliberately not solved here: `ScheduleStore` only
    ever keeps the LATEST result per schedule (see
    tools/scheduler/schedule_store.py), not a full run history -- a
    recurring schedule that fired several times while the client was
    offline is reported with just its most recent result, not each
    individual run. Good enough for "what did I miss," not a complete
    audit log.

    Does NOT include a catch-up for a confirmation_request a disconnected
    client left unanswered -- gui/server.py's websocket_endpoint cancels
    that turn entirely on disconnect (see its own `finally` block), so
    there is nothing pending left to resume by the time a client
    reconnects; the human has to re-ask."""
    since: datetime | None = None
    if last_synced_at:
        try:
            since = datetime.fromisoformat(last_synced_at.replace("Z", "+00:00"))
        except ValueError:
            since = None

    schedules = await ctx.schedule_store.list_schedules()
    schedule_results = []
    for schedule in schedules:
        if not schedule.last_run_at:
            continue
        ran_at = datetime.fromisoformat(schedule.last_run_at)
        if since is not None:
            compare_since = since.replace(tzinfo=None) if since.tzinfo else since
            if ran_at <= compare_since:
                continue
        schedule_results.append(
            {
                "schedule_id": schedule.id,
                "task": schedule.task,
                "summary": schedule.last_result_summary,
                "ran_at": schedule.last_run_at,
            }
        )

    project_status = await service.get_project_status(ctx.cli_context)
    active_project = None
    if project_status.active_slug is not None:
        active_project = next(
            (p for p in project_status.projects if p.slug == project_status.active_slug), None
        )

    return {
        "schedule_results": schedule_results,
        "active_project": (
            {"slug": active_project.slug, "name": active_project.name} if active_project is not None else None
        ),
    }


app = create_app()
